### PR TITLE
Add mail, pack, intermediate folder and disabling transaction log support

### LINKED ISSUE #23: Add support for e-mail reporting.
probably using MAILTO feature in crontab

### PR DESCRIPTION
**Pull request by pfeigl**
This PR adds the following functionality

* Support for sending backup reports via e-mail (When enabled, ALL backup results are sent, not only failures)
* Support for packing (zip or tar.gz) of backup files. 
* Support for setting a zip password (zip only)
* When packing is enabled, backup files are created with a intermediate folder (`/backup_tmp`)
* Support to disable generation of transaction logs

Remarks:
* Mailing has been implemented through `msmtp`
* Mailing config is created in entrypoint script
* We actually implemented the stuff in various feature branches, but due to alot of merge conflicts between those changes, I decided to send everything in one single PR to save you guys the conflict resolutions
* We added a small `development environment`. Look at the `sql-backup-dev` folder. Essentially it's just a docker-compose which 
  * builds upon the Dockerfile of the project
  * builds a sample SQL server which contains the standard `AdventureWorks2019` database
  * maps the `backup.sh` script into the backup container (this allows for editing the script from any IDE outside and run it within the container)
  * We also added a `.env.example` file which needs to be renamed to `.env` for development.

Please let us know if you want anything changed. We tested quite a few combinations of the new features and everything seems to work ok.

Fixes #23 #22 #21 #24

### CODE REVIEW

**Comment by eoehen** [comment]
@pfeigl  Thank you very much for your contribution.  We would like to have one PR for each Issue. The changes per issue are easier to define, the reviews are lighter and the risk is lower.

Do you have the possibility to split your pullrequest for each issue?

**Comment by pfeigl** [comment]
@eoehen That's actually not too easy anymore :-( We fixed a few bugs in the merge process and all feature changes were based on the common addition of the "dev environment".

Is there any chance to get it reviewed in it's current state? Tbh I'm a little short on time to get it refactored again into completly standalone PRs.

**Comment by eoehen** [comment]
@pfeigl Do you agree if we do this for you?

**Comment by pfeigl** [comment]
This would be really great!

**Review by eoehen — CHANGES_REQUESTED** [review]
Blocked because the this PR must be splittd.

**Comment by eoehen** [comment]
@pfeigl Your changes have been merged, thanks for your contribution 👍
Release [0.3.0](https://hub.docker.com/r/bbtsoftwareag/mssql-backup) is published.

**Comment by eoehen** [comment]
@pfeigl IMHO you can close this PR.

**Comment by pfeigl** [comment]
Thanks for all the cleanup work and releasing everything so fast!

**Pull request closed without merging**
