### PR TITLE
Send cron log to stdout and stderr output streams

### LINKED ISSUE #39: Send log to stdout and stderr output streams only.
If we add the parameter (-a) for append the logfile we have no control about the log file size.
We have to think how we can limite the log file size, before we activate this parameter.

- Remove support for write cron log file.
- Support to send log information to stdout and stderr output streams.

Feedback from @pfeigl in #37.

### PR DESCRIPTION
**Pull request by eoehen**
- Remove support for write cron log file.
- Send logs to the stdout and stderr output stream.

Close #39

### CODE REVIEW

**Comment by eoehen** [comment]
@pfeigl Logs are only send to the stdout and stderr output stream.  A log file inside in the backup container is no longer supported.

I also add some documentation for the example [here](https://github.com/bbtsoftware/docker-mssql-backup/tree/feature/Log-to-stdout/example#logging)

Thank you for your feedback.

**Review by christianbumann — APPROVED** [review]
LGTM

**Comment by pfeigl** [comment]
Cool change, definately gonna update our backup to the latest version with this :)

**Comment by eoehen** [comment]
> 
> 
> Cool change, definately gonna update our backup to the latest version with this :)

## Version 0.4.0 is released.
https://github.com/bbtsoftware/docker-mssql-backup/releases/tag/0.4.0
https://hub.docker.com/r/bbtsoftwareag/mssql-backup/tags?page=1&ordering=last_updated&name=0.4.0

**Pull request merged**
